update

diff --git a/dejavu.install b/dejavu.install
--- a/dejavu.install
+++ b/dejavu.install
@@ -5,16 +5,21 @@ _ent_0=$(readlink -fn -- "$0") || _ent_0=''
 PRG=${_ent_0##*/} 
 PRGDIR=${_ent_0%/*}
 PRGNAME="DéjàVu"
+SHAREDIR=/usr/share/dejavu
+REPOSITORY='https://github.com/GaryDean/dejavu.ai.git'
 Version=0.8
 
 dejavu_help() {
 cat <<-EOT
 	Name    : $PRGNAME vs $Version
 	Script  : $PRG
-	Desc    : Installation Script for $PRGNAME
+	Desc    : Installation Script for $PRGNAME GPT-3 Terminal
 	Synopsis: $PRG [Options]
 	Options : -v|--verbose   Verbose on (default)
-	        : -q|--quiet     Verbose off
+	        : -q|--quiet     Verbose off. 
+	        :                If environment key OPENAI_API_KEY
+	        :                has already been set you will not 
+	        :                be prompted to input it.
 	        : -V|--version   Print version.
 	Requires: python 3, pip, openai API key
 	See Also: https://openai.com
@@ -30,10 +35,17 @@ main() {
 	fi
 	
 	local -a args=() 
-	local verbose_=1 quiet_='q'
+	local verbose_=1 quiet_='' tempdir
 	while (($#)); do case "$1" in
-		-v|--verbose)		verbose_=1; quiet_='q' ;;
-		-q|--quiet)			verbose_=0; quiet_='qqq' ;;
+		--pid)					[[ -n "$2" ]] && kill -9 "$2" > /dev/null 2>&1 
+										shift
+										;;
+		-u|--upgrade)		tempdir="/tmp/$PRG-upgrade-$RANDOM"
+										git clone "$REPOSITORY" "$tempdir" || exit
+										"$tempdir/$PRG".install --pid "$$" -"$( ((verbose_)) && echo 'v' || echo 'q')"
+										;;
+		-v|--verbose)		verbose_=1; quiet_='' ;;
+		-q|--quiet)			verbose_=0; quiet_='qq' ;;
 		-V|--version)		echo "$PRGNAME vs $Version"; return 0 ;;
 		-h|--help)			dejavu_help; return 0 ;;
 		-[vqVh]*)				#shellcheck disable=SC2046 # de-aggregate aggregated short options
@@ -66,27 +78,29 @@ main() {
 	fi
 	OPENAI_ORGANIZATION_ID="$key"
 
-	sudo apt install -"$quiet_" python3 pip git
-	sudo pip install -"$quiet_" --upgrade --no-color pip
-	sudo pip install -"$quiet_" --upgrade --no-color openai
+	sudo apt update -q"$quiet_"
+	sudo apt install -q"$quiet_" python3 pip git
+	sudo pip install -q"$quiet_" --upgrade --no-color pip
+	sudo pip install -q"$quiet_" --upgrade --no-color openai
 
-	sudo mkdir -p /usr/share/dejavu.ai
-	sudo chmod 775 /usr/share/dejavu.ai
-	sudo cp -p "$PRGDIR"/*.dejavu.txt /usr/share/dejavu.ai/
-	sudo cp -p "$PRGDIR"/README.md /usr/share/dejavu.ai/
-	sudo cp -p "$PRGDIR"/LICENCE /usr/share/dejavu.ai/
-	sudo cp -p "$PRGDIR/dejavu" "$PRGDIR/dejavu.install" /usr/share/dejavu.ai/
+	sudo mkdir -p "$SHAREDIR"
+	sudo chmod 775 "$SHAREDIR"
+
+	sudo cp -p "$PRGDIR"/*.dejavu.txt "$SHAREDIR"/
+	sudo cp -p "$PRGDIR"/README.md "$SHAREDIR"/
+	sudo cp -p "$PRGDIR"/LICENCE "$SHAREDIR"/
+	sudo cp -p "$PRGDIR/dejavu" "$PRGDIR/dejavu.install" "$SHAREDIR"/
 	
 	sudo cp "$PRGDIR/dejavu" /usr/local/bin/dejavu
 	sudo chmod 775 "/usr/local/bin/dejavu"
 
 	# ~/.bashrc /etc/bash.bashrc
 	local tmpfile file
+	tmpfile="/tmp/$PRG-$RANDOM"
 	for file in "$HOME/.bashrc" /etc/bash.bashrc; do
 		((verbose_)) && echo "Modifying '$file'"
-		[[ ! -f "$file" ]] && continue
+		[[ ! -f "$file" ]] && echo "# This file created by $PRG ($PRGNAME)" > "$file"
 		
-		tmpfile="/tmp/$PRG-$RANDOM"
 		grep -v '^[[:blank:]]*OPENAI_API_KEY=\|^[[:blank:]]*OPENAI_ORGANIZATION_ID=\|^[[:blank:]]*export OPENAI_' "$file" \
 				>"$tmpfile"
 		(	echo "OPENAI_API_KEY=\"$OPENAI_API_KEY\"" 
@@ -98,14 +112,15 @@ main() {
 		) >>"$tmpfile"
 		sudo chmod --reference="$file" "$tmpfile"
 		sudo chown --reference="$file" "$tmpfile"
-		#sudo cp -p "$file" "${file}~"	|| { echo 2> "Could not backup '$file' to '${file}~'!"; exit 1; }
-		sudo mv --backup "$tmpfile" "$file"			|| { echo 2> "'$tmpfile' could not be moved to '$file'!"; exit 1; }
+		sudo mv --backup "$tmpfile" "$file" \
+				|| { echo 2> "'$tmpfile' could not be moved to '$file'!"; exit 1; }
 	done
 		
 	if ((verbose_)); then
 		echo
 		echo "$PRGNAME installed."
 		echo "To run, enter 'dejavu'"
+		echo 'Have fun!'
 	fi
 }
 
